Vidly3/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Vidly3.Models
{
    public class Customer
    {
        public int Id { get;set; }
        public string Name { get; set; }

    }
}

Vidly3/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Vidly3.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Vidly3/Models/RandomMovieViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Vidly3.Models;

namespace Vidly3.ViewModels
{
    public class RandomMovieViewModel
    {
        public Movie Movie { get; set; }
        public List <Customer> customers { get; set; }


    }
}

Vidly3/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Vidly3.Models;
using System.Web.Mvc;

namespace Vidly3.Controllers
{
    public class CustomersController : Controller
    {
        // GET: Customers
        public ActionResult Index()
        {
            var customers = GetCustomers();

            return View(customers);
        }

        public ActionResult Details(int id) { 

              var customer = GetCustomers().SingleOrDefault(c => c.Id == id);
            if (customer == null)
                return HttpNotFound();

            return View(customer);
    }

    public IEnumerable<Customer> GetCustomers()
        {
            return new List<Customer>
            {
            new Customer { Id = 1, Name = "John Smith" },
            new Customer { Id = 2, Name = "Hary Williams" }
            };
        }
    }
}

Vidly3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Vidly3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Vidly3/Controllers/MoviesController.cs
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using Vidly3.Models;
using Vidly3.ViewModels;

namespace Vidly3.Controllers
{
    public class MoviesController : Controller
    {
        public ActionResult Details(int id)
        {
            var movie = GetMovies().SingleOrDefault(m => m.Id == id);

            if (movie == null)
                return HttpNotFound();

            return View(movie);
        }
        public ViewResult Index()
        {
            var movies = GetMovies();

            return View(movies);
        }

        private List<Movie> GetMovies()
        {
            return new List<Movie>
            {
                new Movie { Id = 1, Name = "Sherlock" },
                new Movie { Id = 2, Name = "The Three Stooges" }
            };
        }
        // GET: Movies
        /*     public ActionResult Random()
             {
                 var movie = new Movie { Name = "Sherlock Hommos" };
                 var customers = new List<Customer>
                 {
                     new Customer{Name="Muhammad "},
                     new Customer{Name="Customer 2"}

                 };
                 var viewModel = new RandomMovieViewModel
                 {
                     Movie = movie,
                     customers=customers
                 };
                 return View(viewModel);
                 return View(movie);
                 //return Content("Hello BItches ");
                 //return new EmptyResult();
             }



        /*     public ActionResult ht()
             {
                 return new HttpNotFoundResult();
             }
             public ActionResult Index(int? pageIndex,string sortBy)
             {
                 if (!pageIndex.HasValue)
                     pageIndex = 1;

                 if (String.IsNullOrWhiteSpace(sortBy))
                     sortBy = "Name";
                 return Content(String.Format("pageIndex={0}&sortBy={1}", pageIndex, sortBy));
             }
             [Route ("movies/released/{year}/{month:regex(\\{4}):range(1,12)}")]
             public ActionResult ByReleaseDate(int year, int month)
             {
                 return Content(year + "/" + month);
             }
         }*/
    }
}

Vidly3/Views/Customers/Details.cshtml
@model Vidly3.Models.Customer
@{
    ViewBag.Title = "Details";
}

<h2>@Model.Name</h2>

Vidly3/Views/Customers/Index.cshtml
@model List<Vidly3.Models.Customer>
@{
    ViewBag.Title = "Index";
}

<h1>Customers</h1>

@if (!Model.Any())
{
    <p>We don't have any customers yet.</p>
}
else
{
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Customer</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var customer in Model)
            {
                <tr>
                    <td>@Html.ActionLink(customer.Name, "Details", "Customers", new { id = customer.Id }, null)</td>
                </tr>
            }
        </tbody>
    </table>
}

Vidly3/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Vidly3/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Vidly3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Vidly3/Views/Movies/Details.cshtml
@model Vidly3.Models.Movie

@{
    ViewBag.Title = "Details";
}

    <h1> @Model.Name</h1>

Vidly3/Views/Movies/Index.cshtml
@model List<Vidly3.Models.Movie>

    @{ViewBag.Title = "Index";
    }

    @if (!Model.Any())
    {
        <text>No Movies yet</text>

    }
    else {
    <h2>Movies</h2>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Movie</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var movie in Model)
            {

            <tr>
                <td>@Html.ActionLink(movie.Name, "Details", "Movies", new {id=movie.Id}, null)</td>
            </tr>
            }
        </tbody>
    </table>
    }

Vidly3/Views/Movies/Random.cshtml
@model Vidly3.ViewModels.RandomMovieViewModel

@{
    ViewBag.Title = "Random";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{ 
    var className = Model.customers.Count > 0 ? "popular" : null;

}
<br/>
<h2 class="popular"> @Model.Movie.Name</h2>

@if (Model.customers.Count == 0)
{
    <p>NO one rented this movie ever </p>
}
else
{
    <u>
        @foreach (var customer in Model.customers)
        {
            <li> @customer.Name</li>
        }

    </u>
}

Vidly3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Vidlyyyy</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Vidly3/Views/Shared/_NavBar.cshtml
    <nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-dark">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            </button>
            <a class="navbar-brand" href="/">Vidly</a>
            <div class="navbar-collapse collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav mr-auto">

                    <li class="nav-item"><a href="~/Customers/Index" class="nav-link">Customers</a></li>
                    <li class="nav-item"><a href="~/Movies/Index" class="nav-link">Movies</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right mr-auto">
                    <li class="nav-item"><a href="/Account/Register" id="registerLink" class="nav-link">Register</a></li>
                    <li class="nav-item"><a href="/Account/Login" id="loginLink" class="nav-link">Log in</a></li>
                </ul>
            </div>
        </div>
    </nav>